language: ruby
rvm: 2.2.4
sudo: false
notifications:
  email:
    - arjenderijke@gmail.com
before_install:
- rm Gemfile.lock || true
- gem update bundler
before_script:
- rm -rf ~/build/arjenderijke/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/puppet-${PUPPET_VERSION}/lib/puppet/vendor/*
gemfile:
- Gemfile
env:
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=3.8.7
