language: ruby
rvm: 2.2.4
sudo: false
notifications:
  email:
    - arjenderijke@gmail.com
before_install:
- gem update bundler
before_script:
- rm -rf ~/build/arjenderijke/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/puppet-${PUPPET_VERSION}/lib/puppet/vendor/*
- echo "require 'safe_yaml'" > ~/build/arjenderijke/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/puppet-${PUPPET_VERSION}/lib/puppet/vendor/require_vendored.rb
- gem install --verbose safe_yaml
- cat ${PWD}/vendor/bundle/ruby/2.2.0/gems/puppet-${PUPPET_VERSION}/lib/puppet/vendor/require_vendored.rb
- gem env
env:
  - PUPPET_VERSION=3.7.5
  - PUPPET_VERSION=3.8.1
