language: ruby
rvm: 2.2.4
sudo: false
notifications:
  email:
    - arjenderijke@gmail.com
before_install:
- gem update bundler
before_script:
- rm -rf ~/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/${PUPPET_VERSION}/lib/puppet/vendor/safe_yaml
- rm -rf ~/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/${PUPPET_VERSION}/lib/puppet/vendor/safe_yaml_patches.rb
env:
  - PUPPET_VERSION=3.7.5
  - PUPPET_VERSION=3.8.1
