language: ruby
rvm: 2.2.4
sudo: false
notifications:
  email:
    - arjenderijke@gmail.com
before_install:
- gem update bundler
before_script:
- rm -rf /home/travis/build/arjenderijke/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/${PUPPET_VERSION}/lib/puppet/vendor/*
- ls -R /home/travis/build/arjenderijke/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/${PUPPET_VERSION}/lib/puppet/
- echo "require \'safe_yaml\'" >> /home/travis/build/arjenderijke/puppet-bootstrap_puppetmaster/vendor/bundle/ruby/2.2.0/gems/${PUPPET_VERSION}/lib/puppet/vendor/require_vendored.rb
env:
  - PUPPET_VERSION=3.7.5
  - PUPPET_VERSION=3.8.1
